name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  CI:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        cxx: ['g++']
        cmake_build_type: ['Debug', 'Release']
       
    runs-on: ubuntu-20.04
    container: docker.io/openfoam/openfoam10-paraview510
    steps:
      - name: Checkout AdditiveFOAM
        uses: actions/checkout@v2
      - name: Build AdditiveFOAM
        run: |
          cd $WM_PROJECT_USER_DIR/AdditiveFOAM/applications/solvers/additiveFoam/movingHeatSource
          wmake libso
          cd $WM_PROJECT_USER_DIR/AdditiveFOAM/applications/solvers/additiveFoam
          wmake
      - name: Test AdditiveFOAM
        working-directory: examples
        run: |
          mkdir -p $FOAM_RUN/additivefoam
          cd $FOAM_RUN/additivefoam
          cp -r $WM_PROJECT_USER_DIR/AdditiveFOAM/tutorials/AMB2018-02-B userCase
          cd userCase
          # FIXME: use built-in "additiveFoam" smaller case when created
          blockMesh
          decomposePar
          mpirun -n 6 --oversubscribe additiveFoam -parallel > log.additiveFoam
